import { svelte } from '@sveltejs/vite-plugin-svelte';
import { defineConfig, type Plugin } from 'vite';

// `base` is set from BASE_PATH so the same source builds for GitHub Pages
// (/<repo>/) and for a bare static host (/). See .github/workflows/deploy.yml.
const base = process.env.BASE_PATH ?? '/';

/**
 * Emit an offline-first service worker with the built asset list baked in.
 *
 * Hand-rolled rather than workbox: the whole app is a handful of files, the
 * caching policy matters (network requests to calendars and block explorers
 * must NEVER be served from cache — a stale "confirmed" would be a lie), and
 * this keeps the dependency surface of a security-sensitive app small enough
 * to read in one sitting.
 */
function serviceWorker(): Plugin {
  return {
    name: 'xnotary-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle)
        .filter((f) => /\.(js|css|html|svg|png|woff2?)$/.test(f))
        .map((f) => base + f);
      const precache = [base, `${base}manifest.webmanifest`, ...assets];

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swSource(precache),
      });
    },
  };
}

function swSource(precache: string[]): string {
  return `/* Generated by vite.config.ts — do not edit. */
const CACHE = 'xnotary-${Date.now().toString(36)}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  // Only ever serve this origin's own shell from cache. Calendar submissions
  // and block-explorer lookups must always hit the network: a cached response
  // could make a pending timestamp look confirmed.
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit) return hit;
      return fetch(request).catch(() =>
        request.mode === 'navigate' ? caches.match(${JSON.stringify(precache[0])}) : Promise.reject(),
      );
    }),
  );
});
`;
}

/** Write the web app manifest, so `base` stays the single source of truth. */
function webManifest(): Plugin {
  return {
    name: 'xnotary-manifest',
    apply: 'build',
    generateBundle() {
      this.emitFile({
        type: 'asset',
        fileName: 'manifest.webmanifest',
        source: JSON.stringify(
          {
            name: 'xNotary',
            short_name: 'xNotary',
            description:
              'Self-custodial notarization: hash a file locally, timestamp it on Bitcoin, ' +
              'collect qualified electronic signatures.',
            theme_color: '#0b1020',
            background_color: '#0b1020',
            display: 'standalone',
            start_url: base,
            scope: base,
            icons: [
              { src: `${base}icon-192.png`, sizes: '192x192', type: 'image/png' },
              { src: `${base}icon-512.png`, sizes: '512x512', type: 'image/png' },
              {
                src: `${base}icon-512.png`,
                sizes: '512x512',
                type: 'image/png',
                purpose: 'maskable',
              },
            ],
          },
          null,
          2,
        ),
      });
    },
  };
}

export default defineConfig({
  base,
  plugins: [svelte(), webManifest(), serviceWorker()],
  build: {
    target: 'es2022',
    sourcemap: true,
    rollupOptions: {
      output: {
        // pdf-lib and the certificate builder are only needed once the user
        // acts, so keep them out of the initial payload.
        manualChunks(id) {
          if (id.includes('pdf-lib') || id.includes('@pdf-lib')) return 'pdf';
          if (id.includes('pkijs') || id.includes('asn1js')) return 'pki';
          if (id.includes('opentimestamps') || id.includes('@noble')) return 'ots';
        },
      },
    },
  },
});
